version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mirsadsabovic/myflaskapp:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker run -d - 80:5000  mirsadsabovic/myflaskapp:latest
      - docker ps 
